const { chromium } = require('playwright');
const toon={title:'t',hooks:['a\nb'],cuts:Array.from({length:4},(_,i)=>({role:'r',shot:'미디엄샷',title:i?'':'손님이\n사라졌다',highlight:'',sub:'',bubble:'사장님: 좋아',bubbleSide:'l',sfx:'',direction:'d',panels:'',caption:'',extras:''})),caption:'c',hashtags:'#a',comment:'x',reelCaption:'r',reelHashtags:'#r',reelComment:'rc',endHead:'내일도\n문 열어요',endBtn:'네이버 예약',cast:'',ideas:[]};
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1300,height:1000}}); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.route('**/fonts.googleapis.com/**',r=>r.fulfill({status:200,body:''}));
await p.route('**generativelanguage.googleapis.com/**',r=>r.fulfill({json:{candidates:[{content:{parts:[{text:JSON.stringify(toon)}]}}]}}));
await p.addInitScript(()=>{ if(!sessionStorage.getItem('x')){ sessionStorage.setItem('x',1); localStorage.clear(); localStorage.setItem('instatoon.key','TEST'); localStorage.setItem('instatoon.helpSeen','1'); }});
await p.goto(require('url').pathToFileURL(require('path').resolve(__dirname,'../../site/instatoon.html')).href); await p.waitForTimeout(700);
await p.click('[data-ind="카페"]'); await p.fill('#i-name','우프스낵바'); await p.fill('#i-offer','11월부터 디지털 장부 시스템 도입(시범운영)');
await p.click('#makeBtn'); await p.waitForTimeout(1200); await p.click('.actions [data-step="post"]'); await p.waitForTimeout(400);
await p.click('[data-endon="1"]'); await p.waitForTimeout(200);
console.log('empty fields',await p.$$eval('.endf [data-end]',e=>e.map(x=>x.value).join('|')));
console.log('--- all blank:\n'+await p.$eval('#endPre',e=>e.textContent));
await p.fill('#e-lines','🎁 11월부터 디지털 장부 시스템 도입(시범운영)');
console.log('--- only lines:\n'+await p.$eval('#endPre',e=>e.textContent));
await p.click('[data-act="endSuggest"]'); await p.waitForTimeout(200);
console.log('after suggest',await p.$$eval('.endf [data-end]',e=>e.map(x=>x.value.replace(/\n/g,'/')).join(' | ')));
await p.fill('#e-btn',''); await p.fill('#e-foot','');
console.log('--- no btn/foot:\n'+await p.$eval('#endPre',e=>e.textContent.split('[이 장')[1]));
await p.$eval('.endli',e=>e.scrollIntoView()); await p.screenshot({path:'/tmp/claude-0/z1.png'});
console.log('errors',errs); await b.close(); })();
